services:
  laravel-build:
    build: 
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/
    container_name: yawmod
    working_dir: /var/www
    networks:
      - app-network
    # ports:
    #   - "8000:8000"

  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "443:443"
    links:
      - laravel-build
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   links:
  #     - laravel-build
  #   ports:
  #     - "8989:80"
  #   volumes:
  #     - ./app:/var/www/